invoice_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from invoice_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.hello_world),
    path('invoices/', include(('invoices.urls', 'invoices'), namespace='invoices'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Invoice Admin System'
admin.site.index_title = 'Management'

invoices/urls.py
from django.urls import path

from invoices import views

urlpatterns = [
    path('', views.InvoiceListView.as_view(), name='main'),
    path('create/', views.InvoiceFormView.as_view(), name='create'),
    # path('<pk>/', views.InvoiceTemplateView.as_view(), name='simple_template'),
    path('<pk>/', views.InvoiceAddPositionView.as_view(), name='details'),
    path('<pk>/update/', views.InvoiceUpdateTemplate.as_view(), name='update_invoice'),
    path('<pk>/close',views.InvoiceCloseView.as_view(),name='close_invoice'),
    path('<pk>/delete/<int:position_pk>/',views.InvoiceDeleteView.as_view(),name='delete_postion')
]

invoices/models.py
from django.db import models
from profiles.models import Profile
from receivers.models import Receiver


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return str(self.name)


# Create your models here.
class Invoice(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE)
    invoice_number = models.CharField(max_length=200)
    completion_date = models.DateField()
    issue_date = models.DateField()
    payment_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    closed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)

    def __str__(self):
        return self.invoice_number

    @property  # treat tags as a field
    def tags(self):
        return self.tags.all()

    @property
    def positions(self):
        return self.position_set.all()  # relationships

    @property
    def total_amount(self):
        total = 0
        qs = self.positions
        for pos in qs:
            total += pos.amount
        return total

invoices/forms.py
from django import forms
from .models import Invoice

class InvoiceForm(forms.ModelForm):
    completion_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    issue_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    payment_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = Invoice
        fields = (
            'receiver',
            'invoice_number',
            'completion_date',
            'issue_date',
            'payment_date',
        )

    # def clean_invoice_number(self):
    #     number = self.cleaned_data.get('invoice_number')
    #     if len(number) < 10:
    #         raise ValidationError('Invoice Number too short')

invoices/views.py
from django.contrib import messages
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.views.generic import (
      ListView,
      FormView, 
      TemplateView,
      DetailView, 
      UpdateView,
      RedirectView,
      DeleteView
    )

from invoices.forms import InvoiceForm
from invoices.mixins import InvoiceNotClosed
from invoices.models import Invoice
from positions.forms import AddPositionsForm
from positions.models import Position
from profiles.models import Profile


class InvoiceListView(ListView):
    model = Invoice
    paginate_by = 4
    template_name = "invoices/main.html"

    def get_queryset(self):
        profile = get_object_or_404(Profile, user=self.request.user)

        return super().get_queryset().filter(profile=profile).order_by('-created_at')


class InvoiceFormView(FormView):
    form_class = InvoiceForm
    template_name = 'invoices/create.html'
    i_instance = None

    def get_success_url(self):
        return reverse('invoices:details', kwargs={'pk': self.i_instance.pk})

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        instance = form.save(commit=False)
        instance.profile = profile
        form.save()
        self.i_instance = instance
        return super().form_valid(form)


class InvoiceAddPositionView(InvoiceNotClosed, FormView):
    form_class = AddPositionsForm
    template_name = 'invoices/details.html'

    def form_valid(self, form):
        invoice_pk = self.kwargs.get('pk')
        invoice = Invoice.objects.get(pk= invoice_pk)
        instance = form.save(commit=False)
        instance.invoice = invoice
        form.save()
        messages.info(self.request, f'Invoice position added successfully. {instance.title}')
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.path

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        invoice_obj = Invoice.objects.get(pk = self.kwargs.get('pk'))
        positons = invoice_obj.positions
        context["obj"] = invoice_obj 
        context["positions"] = positons 
        return context
    
class InvoiceTemplateView(DetailView):
    model = Invoice
    template_name = 'invoices/simple_template.html'


class InvoiceUpdateTemplate(InvoiceNotClosed,UpdateView):
    model = Invoice
    template_name = 'invoices/update.html'
    form_class = InvoiceForm
    success_url = reverse_lazy('invoices:main')

    def form_valid(self, form):
        instance = form.save()
        messages.info(self.request, f"Invoice updated successfully --- {instance.invoice_number}")
        return super(InvoiceUpdateTemplate, self).form_valid(form)


class InvoiceCloseView(RedirectView):
    pattern_name = 'invoices:details'

    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Invoice.objects.get(pk=pk)
        obj.closed = True
        obj.save()
        return super().get_redirect_url(*args, **kwargs)

class InvoiceDeleteView(InvoiceNotClosed,DeleteView):
    model = Position

    template_name = 'invoices/position_confirm_delete.html'

    def get_object(self):
        pk = self.kwargs.get('position_pk')
        obj = Position.objects.get(pk=pk) 
        return obj

    def get_success_url(self):
        messages.info(self.request, f'Position deleted successfully {self.object.title}')
        return reverse('invoices:details', kwargs={'pk':self.object.invoice.pk})

invoices/templates/invoices/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
 Invoice
{% endblock title %}

{% block content %}
 <form method="post" action="">
     {% csrf_token %}
    {{ form |crispy }}
     <button type="submit" class="btn btn-primary mt-3"> save</button>
 </form>
{% endblock content %}

invoices/templates/invoices/details.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %} Details{% endblock title %}

{% block content %}
   
    {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'info' %}
                <div class="alert alert-primary mt-2">
                    {{ message }}
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

  <!-- Modal -->
  <div class="modal fade" id="addPositionModal" tabindex="-1" role="dialog" aria-labelledby="addPositionModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{{ obj.invoice_number }}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="post" action="">
                {% csrf_token %}
            <div class="modal-body">
                {{form |crispy}}
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
      </div>
    </div>
  </div>

  <div class="modal fade" id="closeInvoiceModal" tabindex="-1" role="dialog" aria-labelledby="closeInvoiceModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{{obj.invoice_number}}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          Are you sure you want to close invoice number --- {{obj.invoice_number}} ?
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a  href="{% url 'invoices:close_invoice' obj.pk %}" type="submit" class="btn btn-warning">Yes</a>
        </div>
      </div>
    </div>
  </div>

  <div>
    {% if not obj.closed %}
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addPositionModal">
        Add position
      </button>
    
      <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#closeInvoiceModal">
        Close Invoice
      </button>
    {% else %}
      <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#closeInvoiceModal">
        PDF
      </button>
    {% endif %}
  </div>



   <div class="mt-3">
        <h3>Receiver: {{obj.receiver.name}}</h3>
        <hr/>

        <h2>Postions</h2>
        {% if positions %}
        <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Amount</th>
                <th scope="col">Delete</th>
              </tr>
            </thead>
            <tbody>
                {% for position in positions %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{position.title}}</td>
                        <td>{{position.description}}</td>
                        <td>${{position.amount}}</td>
                        <td>
                            {% if not obj.closed %}
                                <a href="{% url 'invoices:delete_postion' obj.pk position.pk %}" class="btn btn-danger">x</a>
                            {% endif %} 
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
          </table>
          <div class="mt-2 text-end">
             <h2>Total Amount: ${{obj.total_amount}}</h2>
        </div>
          {% else %}
            <p>No positions for this invoice .... </p>
        {% endif %}
   </div

{% endblock content %}

invoices/templates/invoices/main.html
{% extends "base.html" %}

{% block title %}
 Invoice
{% endblock title %}

{% block content %}

  {% if messages %}
    {% for message in messages %}
      {% if message.tags == 'info' %}
         <div class="alert alert-primary mt-2">
             {{ message }}
         </div>
      {% endif %}
    {% endfor %}
  {% endif %}

  {% if object_list %}
      {% for invoice in object_list %}
          <div class="card mb-2" style="width:100%">
              <div class="card-body">
                  <h5>{{ invoice.invoice_number }} - {{ invoice.receiver.name }}</h5>
                  <div class="card-text">
                     Completion date: {{ invoice.completion_date}}
                  </div>
                  <div class="text-muted">
                      Total Amount: ${{ invoice.total_amount }}
                  </div>
                  <div class="mt-2">
                      {% if not invoice.closed %}
                        <a href="{% url 'invoices:update_invoice' invoice.pk %}" class="btn btn-primary">Update</a>
                      {% endif %}
                      <a href="{% url 'invoices:details' invoice.pk %}" class="btn btn-info">Details</a>
                  </div>
            </div>
          </div>
     {% endfor %}
  {% else %}
      <h3>No invoices created </h3>
  {% endif %}

   {% if is_paginated %}
      <nav aria-label=" invoice pagination">
          <ul class="pagination">

                <li class="page-item {% if page_obj.has_previous %} {% else %} disabled {% endif %}">
                  <a {% if page_obj.has_previous %}
                     href="?page={{ page_obj.previous_page_number }}"
                     {% endif %}
                     class="page-link" tabindex="-1">Previous</a>
                </li>

                {% for page in paginator.page_range %}
                  <li class="page-item">
                    <a class="page-link {% if page_obj.number == page %} active {% endif %}" href="?page={{ page }}">{{page}}</a>
                 </li>
                {% endfor%}

              {% if page_obj.has_next %}
                 <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                 </li>
                 <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                 </li>
              {% endif %}

          </ul>
    </nav>
   {% endif %}
{% endblock content %}

invoices/templates/invoices/position_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
   <form action='' method='post'>
      {% csrf_token %}
      <p> Are you sure you want to delete position: 
        <b>{{object.title}} </b>?</p>
      <button type='submit' class='btn btn-danger' >Delete</button>
   </form> 
{% endblock content %}

invoices/templates/invoices/simple_template.html
{% extends "base.html" %}

{% block title %}
 Invoice
{% endblock title %}

{% block content %}
   {{ object.pk }} - {{ object.invoice_number }}
{% endblock content %}

invoices/templates/invoices/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
 Invoice - update
{% endblock title %}

{% block content %}
 <form method="post" action="">
     {% csrf_token %}
    {{ form |crispy }}
     <button type="submit" class="btn btn-primary mt-3"> Update</button>
 </form>
{% endblock content %}