invoice_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from invoice_project import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.hello_world),
    path('invoices/', include(('invoices.urls', 'invoices'), namespace='invoices'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = 'Invoice Admin System'
admin.site.index_title = 'Management'

invoices/urls.py
from django.urls import path

from invoices import views

urlpatterns = [
    path('', views.InvoiceListView.as_view(), name='main'),
    path('create/', views.InvoiceFormView.as_view(), name='create'),
    # path('<pk>/', views.InvoiceTemplateView.as_view(), name='simple_template'),
    path('<pk>/', views.InvoiceAddPositionView.as_view(), name='details'),
    path('<pk>/update/', views.InvoiceUpdateTemplate.as_view(), name='update_invoice'),
    path('<pk>/close',views.InvoiceCloseView.as_view(),name='close_invoice'),
    path('<pk>/delete/<int:position_pk>/',views.InvoiceDeleteView.as_view(),name='delete_postion')
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}">
    <title>Invoice App | {% block title%}{% endblock title%}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
          crossorigin="anonymous">
    <link href="{% static 'style.css' %} " rel="stylesheet">
  </head>
  <body>
     {% include 'navbar.html' %}
     <div class="container mt-3">
        {% block content %}

       {% endblock content%}
     </div>
     <script src="https://code.jquery.com/jquery-3.1.1.min.js">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js">
    </script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js">
    </script>
  </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}
 test
{% endblock title %}

{% block content %}
hello World
{% endblock content %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-primary">
    <div class="container">
        <a class="navbar-brand" href="{% url 'invoices:main' %}">Invoice App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--                <li class="nav-item">-->
<!--                    <a class="nav-link active" aria-current="page" href="#">Home</a>-->
<!--                </li>-->
            </ul>
            <ul class="navbar-nav">
                 <li class="nav-item">
                    <a class="nav-link" href="{% url 'invoices:create' %}">Create New Invoice</a>
             </li>
            </ul>
        </div>
    </div>
</nav>